### ISSUE TITLE
How to change res of Chrome within noVNC

### ISSUE THREAD

**Issue by phere-x** [ich777/docker-ungoogled-chromium#5]
I'm not sure if it was the proper way but I modified `start-server.sh` & added in the new resolution values & then mounted it. Nothing changed.

---
docker compsoe:
```
  uch:
    container_name: uch1
    restart: "unless-stopped"
    image: "ich777/ungoogled-chromium"
    shm_size: "2gb"
    ports:
      - "6901:8080"
    environment:
      UID: 1000
      GID: 1000
      UMASK: 000
      DATA_PERM: 770
    volumes:
      - /data/dock/uch/:/ungoogledchromium
      - /data/dock/uch/scripts/:/opt/scripts
```
