### ISSUE TITLE
Is sound not available using this image?

### ISSUE THREAD

**Issue by phere-x** [ich777/docker-ungoogled-chromium#6]
I am running a docker container on a headless Ubuntu server (`Ubuntu 22.04.2 LTS`)

docker compose:
```
  uch:
    container_name: uch1
    restart: "unless-stopped"
    image: "ich777/ungoogled-chromium"
    shm_size: "2gb"
    ports:
      - "6901:8080"
    environment:
      UID: 1000
      GID: 1000
      UMASK: 000
      DATA_PERM: 770
    volumes:
      - /data/dock/uch/:/ungoogledchromium
```
